[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-framework", "-C", "link-arg=AppKit", "-C", "link-arg=-framework", "-C", "link-arg=Foundation"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-framework", "-C", "link-arg=AppKit", "-C", "link-arg=-framework", "-C", "link-arg=Foundation"]
